
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - script: echo Hello, build!
      displayName: 'Run build'

- stage: DevDEploy
  jobs:
  - job: build
    steps:
    - script: echo Hello, DevDEploy!
      displayName: 'Run a DevDEploy'

- stage: ProdDeploy
  jobs:
  - job: PROD
    steps:
    - script: echo Hello, ProdDeploy!
      displayName: 'Run ProdDeploy'
